fix: prevent putDimensions from storing duplicate dimensions
awslabs/aws-embedded-metrics-java pull request #88
Opened 2021-11-22 19:27 UTC by aaronlna

## Issue

https://github.com/awslabs/aws-embedded-metrics-java/issues/35 (related)

## Description of changes

This is the Java-equivalent bug-fix for prior issue in Node:
https://github.com/awslabs/aws-embedded-metrics-node/issues/20

New conditions check for any matching dimension set before
skipping put dimensions. This prevents duplicates from being stored.

## Description of how you validated changes

Unit test updated to address edge case;
multiple dimension sets of variable size are added and checked.

Ran integration tests using Docker and compared results in CloudWatch.

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-01-28 10:42 UTC, miguelcss commented
Ping, anyone at aws-embedded-metrics-java project with admin permissions can have a look at this PR? 
Some more coming up :)

2022-08-09 17:45 UTC, markkuhn requested changes

2022-08-09 17:45 UTC, markkuhn commented on src/test/java/software/amazon/cloudwatchlogs/emf/model/MetricDirectiveTest.java
> +                "{\"Dimensions\":[[],[\"Region\"],[\"Instance\",\"Region\"],[\"Instance\"]],\"Metrics\":[],\"Namespace\":\"aws-embedded-metrics\"}");
Swap these 2 arguments so they are in the correct order: expected value, actual value.

```suggestion
                "{\"Dimensions\":[[],[\"Region\"],[\"Instance\",\"Region\"],[\"Instance\"]],\"Metrics\":[],\"Namespace\":\"aws-embedded-metrics\"}",
                serializedMetricDirective);
```

2022-08-09 17:45 UTC, markkuhn commented on src/test/java/software/amazon/cloudwatchlogs/emf/model/MetricDirectiveTest.java
> +                "{\"Dimensions\":[[\"Instance\",\"Region\"],[\"Instance\"],[\"Region\"],[]],\"Metrics\":[],\"Namespace\":\"aws-embedded-metrics\"}");
Swap these 2 arguments so they are in the correct order: expected value, actual value.

```suggestion
                "{\"Dimensions\":[[\"Instance\",\"Region\"],[\"Instance\"],[\"Region\"],[]],\"Metrics\":[],\"Namespace\":\"aws-embedded-metrics\"}",
                serializedMetricDirective);
```

2022-08-11 22:05 UTC, Stephen-Bao approved these changes

2022-08-15 16:20 UTC, markkuhn approved these changes

2022-08-15 16:22 UTC, merged